version: '2.1'
services:
  cookiesWorld_ServerInfo:
    build: .
    image: cookiesworld/serverinfo
    hostname: www.kuckelsberg.de
    container_name: cookiesWorld_ServerInfo
    restart: always
    ports:
      - 4713:4713
